# 02_CLEAN — Traffy Fondue Data Preperation

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load data
df = pd.read_csv('../data_raw/bangkok_traffy_raw.csv', low_memory=False)

df.head()

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
0,2021-FYJTFP,{ความสะอาด},เขตบางซื่อ,ขยะเยอะ,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53084,13.81865",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,NaN,กรุงเทพมหานคร,2021-09-03 12:51:09.453003+00,เสร็จสิ้น,NaN,0.0,2022-06-04 15:34:14.609206+00
1,2021-CGPMUN,"{น้ำท่วม,ร้องเรียน}","เขตประเวศ,ฝ่ายโยธา เขตประเวศ",น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.66709,13.67891",189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-09-19 14:56:08.924992+00,เสร็จสิ้น,4.0,0.0,2022-06-21 08:21:09.532782+00
2,2021-7XATFA,{สะพาน},เขตสาทร,สะพานลอยปรับปรุงไม่เสร็จตามกำหนด\nปากซอย สาทร12,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52649,13.72060",191/1 ถนน สาทรเหนือ แขวง สีลม เขตบางรัก กรุงเท...,ยานนาวา,สาทร,กรุงเทพมหานคร,2021-09-26 05:03:52.594898+00,เสร็จสิ้น,NaN,0.0,2022-06-06 01:17:12.272904+00
3,2021-9U2NJT,{น้ำท่วม},"เขตบางซื่อ,ฝ่ายโยธา เขตบางซื่อ",น้ำท่วม,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53099,13.81853",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,NaN,กรุงเทพมหานคร,2021-10-14 10:45:27.713884+00,เสร็จสิ้น,NaN,0.0,2022-09-08 08:35:43.784519+00
4,2021-DVEWYM,"{น้ำท่วม,ถนน}","เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.59165,13.82280",702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2021-12-09 12:29:08.408763+00,เสร็จสิ้น,5.0,0.0,2022-08-12 07:18:44.884945+00

# Standardize Missing Values

In [2]:
missing_tokens = ["", " ", "N/A", "n/a", "na", "null", "None", "-", "ไม่ระบุ", "{}"]
df = df.replace(missing_tokens, np.nan)
df.head(10)

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity
0,2021-FYJTFP,{ความสะอาด},เขตบางซื่อ,ขยะเยอะ,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53084,13.81865",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,NaN,กรุงเทพมหานคร,2021-09-03 12:51:09.453003+00,เสร็จสิ้น,NaN,0.0,2022-06-04 15:34:14.609206+00
1,2021-CGPMUN,"{น้ำท่วม,ร้องเรียน}","เขตประเวศ,ฝ่ายโยธา เขตประเวศ",น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.66709,13.67891",189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-09-19 14:56:08.924992+00,เสร็จสิ้น,4.0,0.0,2022-06-21 08:21:09.532782+00
2,2021-7XATFA,{สะพาน},เขตสาทร,สะพานลอยปรับปรุงไม่เสร็จตามกำหนด\nปากซอย สาทร12,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52649,13.72060",191/1 ถนน สาทรเหนือ แขวง สีลม เขตบางรัก กรุงเท...,ยานนาวา,สาทร,กรุงเทพมหานคร,2021-09-26 05:03:52.594898+00,เสร็จสิ้น,NaN,0.0,2022-06-06 01:17:12.272904+00
3,2021-9U2NJT,{น้ำท่วม},"เขตบางซื่อ,ฝ่ายโยธา เขตบางซื่อ",น้ำท่วม,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53099,13.81853",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,NaN,NaN,กรุงเทพมหานคร,2021-10-14 10:45:27.713884+00,เสร็จสิ้น,NaN,0.0,2022-09-08 08:35:43.784519+00
4,2021-DVEWYM,"{น้ำท่วม,ถนน}","เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.59165,13.82280",702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2021-12-09 12:29:08.408763+00,เสร็จสิ้น,5.0,0.0,2022-08-12 07:18:44.884945+00
5,2021-4D9Y98,NaN,"เขตลาดพร้าว,การไฟฟ้านครหลวง เขตนวลจันทร์",หน้าปากซอย ลาดพร้าววังหิน26,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.59131,13.80910",17/73 17/73 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขต...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2021-12-13 05:53:36.861064+00,เสร็จสิ้น,NaN,0.0,2023-03-14 12:09:14.947437+00
6,2021-7U9RED,NaN,เขตดุสิต,ยังไม่มีหน่วยงานไหนมาดูแลครับ รถจะเชี่ยวหลายคน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.50848,13.77832",627 ถนนสามเสน แขวง ดุสิต เขตดุสิต กรุงเทพมหานค...,ดุสิต,ดุสิต,กรุงเทพมหานคร,2021-12-17 08:46:02.610983+00,เสร็จสิ้น,5.0,0.0,2023-05-17 06:11:32.463984+00
7,2021-8N9ZP8,{ความสะอาด},"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ,ฝ่ายรักษาความสะ...",คนเอาขยะมาทิ้งจนกลายเป็นกองขยะค่ะ,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.64690,13.67083",110 ซอย มีสุข แขวง หนองบอน เขต ประเวศ กรุงเทพม...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-12-18 14:50:52.437512+00,เสร็จสิ้น,2.0,0.0,2024-11-26 04:17:39.760344+00
8,2021-7K6QA3,NaN,"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ",ระยะหลังๆ นี้ พบเจอรถสิบล้อขนดิน ใส่ยางบังโคลน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.65617,13.72812",208/22 ถ. พัฒนาการ แขวง ประเวศ เขต ประเวศ กรุง...,ประเวศ,ประเวศ,กรุงเทพมหานคร,2021-12-21 23:03:58.450912+00,เสร็จสิ้น,2.0,0.0,2022-06-24 06:32:34.671236+00
9,2021-8BTWZB,{ท่อระบายน้ำ},"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",ขอแจ้งเรื่องท่อระบายน้ำบนถนนในซอยเสียหาย เป็นร...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.65440,13.68158",70 ซอย เฉลิมพระเกียรติ ร. 9 แขวง หนองบอน เขต ป...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-12-22 10:15:33.294829+00,เสร็จสิ้น,5.0,0.0,2022-06-20 13:12:04.99444+00

# coordinate split
จาก dataset คาดว่า latitude longitude สลับกัน

In [3]:
def split_coords(coords):
    if pd.isna(coords) or not isinstance(coords, str) or ',' not in coords:
        return pd.Series([np.nan, np.nan])
    lat, lon = coords.split(',', 1)
    try:
        return pd.Series([float(lon), float(lat)])
    except:
        return pd.Series([np.nan, np.nan])

df[['lat', 'lon']] = df['coords'].apply(split_coords)
 
# Remove invalid Thailand coordinates
df.loc[(df.lat < 5) | (df.lat > 21), ['lat']] = np.nan
df.loc[(df.lon < 97) | (df.lon > 106), ['lon']] = np.nan

df[['lat', 'lon']].head(20)

         lat        lon
0   13.81865  100.53084
1   13.67891  100.66709
2   13.72060  100.52649
3   13.81853  100.53099
4   13.82280  100.59165
5   13.80910  100.59131
6   13.77832  100.50848
7   13.67083  100.64690
8   13.72812  100.65617
9   13.68158  100.65440
10  13.68735  100.64844
11  13.71887  100.68837
12  13.70716  100.53764
13  13.70950  100.52674
14  13.70967  100.52678
15  13.70566  100.53025
16  13.68814  100.65816
17  13.70569  100.52970
18  13.70611  100.52789
19  13.70615  100.52760

## Fill count_reopen Missing

In [4]:
df['count_reopen'] = df['count_reopen'].fillna(0).astype(int)
df['count_reopen'].value_counts().head()

count_reopen
0    708847
1     35839
2      8434
3      3245
4      1504
Name: count, dtype: int64

## Timestamp Cleaning

In [5]:
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
df['last_activity'] = pd.to_datetime(df['last_activity'], errors='coerce')

# For missing last_activity, use timestamp
df['last_activity'] = df['last_activity'].fillna(df['timestamp'])

df[['timestamp','last_activity']].head()

                         timestamp                    last_activity
0 2021-09-03 12:51:09.453003+00:00 2022-06-04 15:34:14.609206+00:00
1 2021-09-19 14:56:08.924992+00:00 2022-06-21 08:21:09.532782+00:00
2 2021-09-26 05:03:52.594898+00:00 2022-06-06 01:17:12.272904+00:00
3 2021-10-14 10:45:27.713884+00:00 2022-09-08 08:35:43.784519+00:00
4 2021-12-09 12:29:08.408763+00:00 2022-08-12 07:18:44.884945+00:00

# column-by-column missing value

In [6]:
df['type'] = df['type'].fillna('Unknown')
# Fill using mode per type
df['type'] = df['type'].fillna('{Unassigned}')
df['comment'] = df['comment'].fillna('')
df['has_photo'] = df['photo'].notna().astype(int)
df['has_photo_after'] = df['photo_after'].notna().astype(int)
df['district'] = df['district'].str.title().fillna('Unknown')
df['subdistrict'] = df['subdistrict'].str.title().fillna('Unknown')
df['star'] = df['star'].fillna(-1).astype(int)
df['last_activity'] = df['last_activity'].fillna(df['timestamp'])
df['state'] = df['state'].fillna('unknown')
df['count_reopen'] = df['count_reopen'].fillna(0).astype(int)

## Feature Engineering
เพิ่มหลังหัวข้อมา

# fix or remove impossible broken rows

In [7]:
print("Dataset shape before cleaning:", df.shape)
df = df.dropna(subset=['ticket_id', 'timestamp', 'lat', 'lon', 'organization'])
df = df[df['province'].str.lower() == 'กรุงเทพมหานคร'].copy()
df = df[df['count_reopen'].fillna(0) >= 0]
df = df.dropna(how='all')
df = df.reset_index(drop=True)
print("Dataset shape after cleaning:", df.shape)
print("Sample rows:")
df.head(40)

Dataset shape before cleaning: (760887, 20)
Dataset shape after cleaning: (630478, 20)
Sample rows:

,ticket_id,type,organization,comment,photo,photo_after,coords,address,subdistrict,district,province,timestamp,state,star,count_reopen,last_activity,lat,lon,has_photo,has_photo_after
0,2021-FYJTFP,{ความสะอาด},เขตบางซื่อ,ขยะเยอะ,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53084,13.81865",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,Unknown,Unknown,กรุงเทพมหานคร,2021-09-03 12:51:09.453003+00:00,เสร็จสิ้น,-1,0,2022-06-04 15:34:14.609206+00:00,13.81865,100.53084,1,0
1,2021-CGPMUN,"{น้ำท่วม,ร้องเรียน}","เขตประเวศ,ฝ่ายโยธา เขตประเวศ",น้ำท่วมเวลาฝนตกและทะลุเข้าบ้านเดือดร้อนมากทุกๆ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.66709,13.67891",189 เฉลิมพระเกียรติ ร.9 แขวง หนองบอน เขต ประเว...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-09-19 14:56:08.924992+00:00,เสร็จสิ้น,4,0,2022-06-21 08:21:09.532782+00:00,13.67891,100.66709,1,1
2,2021-7XATFA,{สะพาน},เขตสาทร,สะพานลอยปรับปรุงไม่เสร็จตามกำหนด\nปากซอย สาทร12,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52649,13.72060",191/1 ถนน สาทรเหนือ แขวง สีลม เขตบางรัก กรุงเท...,ยานนาวา,สาทร,กรุงเทพมหานคร,2021-09-26 05:03:52.594898+00:00,เสร็จสิ้น,-1,0,2022-06-06 01:17:12.272904+00:00,13.72060,100.52649,1,0
3,2021-9U2NJT,{น้ำท่วม},"เขตบางซื่อ,ฝ่ายโยธา เขตบางซื่อ",น้ำท่วม,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53099,13.81853",12/14 ถนน กรุงเทพ- นนทบุรี แขวง บางซื่อ เขตบาง...,Unknown,Unknown,กรุงเทพมหานคร,2021-10-14 10:45:27.713884+00:00,เสร็จสิ้น,-1,0,2022-09-08 08:35:43.784519+00:00,13.81853,100.53099,1,1
4,2021-DVEWYM,"{น้ำท่วม,ถนน}","เขตลาดพร้าว,ฝ่ายโยธา เขตลาดพร้าว",ซอยลาดพร้าววังหิน 75 ถนนลาดพร้าววังหิน แขวงลาด...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.59165,13.82280",702 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขตลาดพร้าว...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2021-12-09 12:29:08.408763+00:00,เสร็จสิ้น,5,0,2022-08-12 07:18:44.884945+00:00,13.82280,100.59165,1,0
5,2021-4D9Y98,Unknown,"เขตลาดพร้าว,การไฟฟ้านครหลวง เขตนวลจันทร์",หน้าปากซอย ลาดพร้าววังหิน26,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.59131,13.80910",17/73 17/73 ถ. ลาดพร้าววังหิน แขวงลาดพร้าว เขต...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2021-12-13 05:53:36.861064+00:00,เสร็จสิ้น,-1,0,2023-03-14 12:09:14.947437+00:00,13.80910,100.59131,1,1
6,2021-7U9RED,Unknown,เขตดุสิต,ยังไม่มีหน่วยงานไหนมาดูแลครับ รถจะเชี่ยวหลายคน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.50848,13.77832",627 ถนนสามเสน แขวง ดุสิต เขตดุสิต กรุงเทพมหานค...,ดุสิต,ดุสิต,กรุงเทพมหานคร,2021-12-17 08:46:02.610983+00:00,เสร็จสิ้น,5,0,2023-05-17 06:11:32.463984+00:00,13.77832,100.50848,1,1
7,2021-8N9ZP8,{ความสะอาด},"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ,ฝ่ายรักษาความสะ...",คนเอาขยะมาทิ้งจนกลายเป็นกองขยะค่ะ,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.64690,13.67083",110 ซอย มีสุข แขวง หนองบอน เขต ประเวศ กรุงเทพม...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-12-18 14:50:52.437512+00:00,เสร็จสิ้น,2,0,2024-11-26 04:17:39.760344+00:00,13.67083,100.64690,1,1
8,2021-7K6QA3,Unknown,"เขตประเวศ,ฝ่ายเทศกิจ เขตประเวศ",ระยะหลังๆ นี้ พบเจอรถสิบล้อขนดิน ใส่ยางบังโคลน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.65617,13.72812",208/22 ถ. พัฒนาการ แขวง ประเวศ เขต ประเวศ กรุง...,ประเวศ,ประเวศ,กรุงเทพมหานคร,2021-12-21 23:03:58.450912+00:00,เสร็จสิ้น,2,0,2022-06-24 06:32:34.671236+00:00,13.72812,100.65617,1,1
9,2021-8BTWZB,{ท่อระบายน้ำ},"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",ขอแจ้งเรื่องท่อระบายน้ำบนถนนในซอยเสียหาย เป็นร...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.65440,13.68158",70 ซอย เฉลิมพระเกียรติ ร. 9 แขวง หนองบอน เขต ป...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-12-22 10:15:33.294829+00:00,เสร็จสิ้น,5,0,2022-06-20 13:12:04.994440+00:00,13.68158,100.65440,1,1
10,2021-AKJBCU,Unknown,"เขตประเวศ,ฝ่ายโยธา เขตประเวศ",แจ้งเรื่องพื้นผิวถนนเสียหาย มีการพยายามซ่อมแซม...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.64844,13.68735",55 ถนน ศรีนครินทร์ แขวง หนองบอน เขต ประเวศ กรุ...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2021-12-23 10:26:48.868250+00:00,เสร็จสิ้น,-1,0,2022-09-28 08:35:36.703421+00:00,13.68735,100.64844,1,1
11,2021-EQWYWT,{ความสะอาด},"เขตประเวศ,สำนักสิ่งแวดล้อม กทม.,ฝ่ายสิ่งแวดล้อ...",ปัญหากลิ่นขยะจากโรงขยะ 800 ตัน อ่อนนุช 86 ครับ,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.68837,13.71887",22/1 ซอย อ่อนนุช 86 แยก 2 แขวง ประเวศ เขต ประเ...,ประเวศ,ประเวศ,กรุงเทพมหานคร,2021-12-28 03:59:06.003252+00:00,เสร็จสิ้น,4,0,2022-07-12 06:50:02.315260+00:00,13.71887,100.68837,1,1
12,2022-7ZTKJV,"{ถนน,ทางเท้า}","เขตสาทร,ฝ่ายโยธา เขตสาทร",บริเวณนราธิวาส แยกถนนจันทน์ ใกล้สวนสาธารณะช่อ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53764,13.70716",แยกจันทน์-นราธิวาส ถนน จันทน์ แขวง ทุ่งมหาเมฆ ...,ทุ่งมหาเมฆ,สาทร,กรุงเทพมหานคร,2022-01-02 10:53:25.580723+00:00,เสร็จสิ้น,-1,0,2022-06-08 05:46:12.776594+00:00,13.70716,100.53764,1,1
13,2022-E24G76,Unknown,"เขตสาทร,ฝ่ายเทศกิจ เขตสาทร",มอเตอร์ไซด์จอดบนทางเท้าเป็นประจำ ฝั่งตรงข้ามตล...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.52674,13.70950",184 ซอย จันทน์ 18/7 แขวง ทุ่งวัดดอน เขต สาทร ก...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-14 01:17:23.873811+00:00,เสร็จสิ้น,-1,0,2022-06-22 08:06:08.170048+00:00,13.70950,100.52674,1,1
14,2022-C37YCA,Unknown,"เขตสาทร,ฝ่ายเทศกิจ เขตสาทร",มอเตอร์ไซด์จอดบนถนน ลดช่องจราจรทำให้การจราจรชะ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52678,13.70967",184 ซอย จันทน์ 18/7 แขวง ทุ่งวัดดอน เขต สาทร ก...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-14 01:18:57.194155+00:00,เสร็จสิ้น,-1,0,2022-06-22 08:10:20.715755+00:00,13.70967,100.52678,1,0
15,2022-HB7Z8A,"{ท่อระบายน้ำ,ทางเท้า}","เขตสาทร,สำนักการระบายน้ำ กทม.,ฝ่ายโยธา เขตสาทร...",ทางเท้าช่วง จันทน์ 18/5 สภาพโอเค แต่ฝาท่อเก่าแ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53025,13.70566",1357/1-4 ซอย จันทน์ 23/2 แขวง ทุ่งวัดดอน เขต ส...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-14 01:32:03.715912+00:00,กำลังดำเนินการ,-1,0,2022-09-15 15:51:15.433811+00:00,13.70566,100.53025,1,0
16,2022-8EW3HK,Unknown,"เขตประเวศ,สำนักสิ่งแวดล้อม กทม.",อยากให้สวนหลวง ร9 และ สวนสาธารณะอื่นๆ ใน กทม เ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.65816,13.68814",444 ซอย หมู่บ้านเสรี แขวง หนองบอน เขต ประเวศ ก...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2022-01-15 12:52:39.805944+00:00,เสร็จสิ้น,-1,0,2022-06-20 07:12:17.332913+00:00,13.68814,100.65816,1,1
17,2022-8PL3NK,"{ถนน,สะพาน}","เขตสาทร,สำนักการจราจรและขนส่ง กรุงเทพมหานคร (ส...",ถนนจันทน์ช่วงสะพานสามถึงจันทน์ 18/5 น่าจะลาดยา...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.52970,13.70569",1357/1-4 ซอย จันทน์ 23/2 แขวง ทุ่งวัดดอน เขต ส...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-16 10:57:39.184772+00:00,เสร็จสิ้น,-1,0,2023-08-18 06:52:20.549786+00:00,13.70569,100.52970,1,1
18,2022-98YDNN,Unknown,เขตสาทร,ปากซอย จันทน์ 18/4 จักรยานยนต์นิยมขึ้นมาจอดบนท...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.52789,13.70611",3 ซอย จันทน์ 18/4 แขวง ทุ่งวัดดอน เขต สาทร กรุ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-16 11:02:48.949248+00:00,เสร็จสิ้น,-1,0,2022-06-09 03:49:13.904316+00:00,13.70611,100.52789,1,1
19,2022-GNTHRA,{สะพาน},"เขตสาทร,ฝ่ายเทศกิจ เขตสาทร",ริมถนน ตรงสะพานสามช่วงจันทน์ 18/6-18/4 ชอบมีรถ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52760,13.70615",3 ซอย จันทน์ 18/4 แขวง ทุ่งวัดดอน เขต สาทร กรุ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-16 11:08:54.141813+00:00,เสร็จสิ้น,-1,0,2022-06-23 08:06:52.928142+00:00,13.70615,100.52760,1,0
20,2022-9EHJW2,"{จราจร,สะพาน,ถนน}","เขตสาทร,สน.ยานนาวา,ฝ่ายเทศกิจ เขตสาทร",บริเวณสะพานสามถนนจันทน์ เป็นจุดเปลี่ยนถ่ายสองแ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52756,13.70611",3 ซอย จันทน์ 18/4 แขวง ทุ่งวัดดอน เขต สาทร กรุ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-16 11:14:00.944767+00:00,เสร็จสิ้น,-1,0,2022-06-22 08:18:08.293672+00:00,13.70611,100.52756,1,0
21,2022-9WYEJE,Unknown,"เขตสาทร,กลุ่มงานสัญญาณไฟจราจร สวจ.สจส. กทม.,สำ...",ไฟคนข้ามถนนติดมาน่าจะเกินปีแจ่ไม่เคยเขียวเลยแด...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52870,13.70590",214 ถนนจันทน์ แขวง ทุ่งวัดดอน เขต สาทร กรุงเทพ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-16 11:17:19.378093+00:00,กำลังดำเนินการ,-1,0,2023-02-15 06:33:23.446107+00:00,13.70590,100.52870,1,0
22,2022-BF7TYV,"{ถนน,ทางเท้า}",เขตสาทร,วินมอไซด์หน้าคอนโดฟิว ถนนจันทน์ จัดตั้งถูกต้อง...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53055,13.70561",1369 ถนนจันทน์ แขวง ทุ่งวัดดอน เขต สาทร กรุงเท...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-17 02:55:44.733889+00:00,เสร็จสิ้น,-1,0,2022-06-22 08:14:15.037827+00:00,13.70561,100.53055,1,1
23,2022-8TPW66,{ทางเท้า},"เขตสาทร,สำนักการโยธา กทม.,ฝ่ายโยธา เขตสาทร",ไม่มีทางลาดจากทางเท้าลงทางม้าลาย ใกล้ไปรษณีย์ย...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53103,13.70545",156 ถนนจันทน์ แขวง ทุ่งวัดดอน เขต สาทร กรุงเทพ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-17 02:57:06.822237+00:00,เสร็จสิ้น,-1,0,2023-04-26 13:18:35.350136+00:00,13.70545,100.53103,1,1
24,2022-RMC3XE,{ความสะอาด},เขตสาทร,จุดทิ้งขยะตรงปากซอยจันทน์ 18 ติดป้ายรถเมล์ ไม่...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.53183,13.70548",134 ซอย จันทน์ 18 แขวง ทุ่งวัดดอน เขต สาทร กรุ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-17 02:59:54.752710+00:00,เสร็จสิ้น,-1,0,2022-06-05 11:41:34.651880+00:00,13.70548,100.53183,1,1
25,2022-9KMF88,{ทางเท้า},"เขตสาทร,ฝ่ายเทศกิจ เขตสาทร",ซอยจันทน์ 16 ซอยขนาด 4 เลนแต่เลนติดบ้านคนกลายเ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53212,13.70578",14 ซ. จันทน์ 16 แขวง ทุ่งวัดดอน เขต สาทร กรุงเ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-17 03:01:52.819295+00:00,เสร็จสิ้น,-1,0,2022-06-22 08:12:25.289345+00:00,13.70578,100.53212,1,0
26,2022-EVNC8T,Unknown,"เขตสาทร,ฝ่ายเทศกิจ เขตสาทร",ซอยจันทน์ 16 มีป้ายห้ามจอดตั้งอยู่ด้วยแต่บังคั...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.53216,13.70566",14 ซ. จันทน์ 16 แขวง ทุ่งวัดดอน เขต สาทร กรุงเ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-17 03:19:43.229481+00:00,เสร็จสิ้น,-1,0,2022-06-22 08:14:41.529943+00:00,13.70566,100.53216,1,0
27,2022-D9Z7ZE,Unknown,"เขตยานนาวา,เขตสาทร,สำนักการจราจรและขนส่ง กรุงเ...",ทางม้าลาย ไปชนเกาะกลางไม่มีทางเดิน แยกจันท สาธุ,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52878,13.70581",214 ถนนจันทน์ แขวง ทุ่งวัดดอน เขต สาทร กรุงเทพ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-01-17 12:47:48.697983+00:00,กำลังดำเนินการ,-1,0,2024-02-02 10:51:45.865074+00:00,13.70581,100.52878,1,0
28,2022-G4Z2FF,Unknown,เขตดุสิต,ตรงแยกวัดเบญ ที่จะเลี้ยวซ้ายไปสวนสัตว์ดุสิตเก่...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.51525,13.76652",แยกวัดเบญจฯ 69 ถ. ศรีอยุธยา แขวง ดุสิต เขตดุสิ...,สวนจิตรลดา,ดุสิต,กรุงเทพมหานคร,2022-01-25 11:17:38.883821+00:00,เสร็จสิ้น,5,0,2022-06-01 04:12:59.848762+00:00,13.76652,100.51525,1,0
29,2022-39BTEG,{ถนน},"เขตลาดพร้าว,สำนักการจราจรและขนส่ง กรุงเทพมหานค...",ส่งรูปทางม้าลายไม่ชัดเจน และรถขายของเพิ่มเติม ...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.61849,13.82484",129 ถ. สุคนธสวัสดิ์ แขวงลาดพร้าว เขตลาดพร้าว ก...,ลาดพร้าว,ลาดพร้าว,กรุงเทพมหานคร,2022-01-26 13:32:37.177987+00:00,เสร็จสิ้น,-1,0,2024-11-13 06:06:16.579351+00:00,13.82484,100.61849,1,1
30,2022-DMG79E,{ความสะอาด},เขตดุสิต,ขยะ,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.51523,13.75824",76 ถนน ลูกหลวง แขวง สี่แยกมหานาค เขตดุสิต กรุง...,สวนจิตรลดา,ดุสิต,กรุงเทพมหานคร,2022-01-28 04:09:47.823237+00:00,เสร็จสิ้น,4,0,2023-05-17 05:16:34.660298+00:00,13.75824,100.51523,1,1
31,2022-E7JRF8,Unknown,เขตดุสิต,ขอบคุณมากค่ะ,https://storage.googleapis.com/traffy_public_b...,NaN,"100.51815,13.78859",142 ซอย องครักษ์ 6 แขวง ถนนนครไชยศรี เขตดุสิต ...,ถนนนครไชยศรี,ดุสิต,กรุงเทพมหานคร,2022-01-29 10:54:11.873046+00:00,เสร็จสิ้น,-1,0,2023-05-17 05:04:03.042764+00:00,13.78859,100.51815,1,0
32,2022-E449PD,{ถนน},"เขตประเวศ,สำนักการจราจรและขนส่ง กรุงเทพมหานคร ...",เส้นทางม้าลายไม่ชัด ตรงหน้าทางเข้าตลาดนัดรถไฟ ...,https://storage.googleapis.com/traffy_public_b...,NaN,"100.64730,13.69141",13/131 ถนน ศรีนครินทร์ แขวง หนองบอน เขต ประเวศ...,หนองบอน,ประเวศ,กรุงเทพมหานคร,2022-01-30 15:43:46.155790+00:00,เสร็จสิ้น,-1,0,2022-06-23 23:48:29.379950+00:00,13.69141,100.64730,1,0
33,2022-FNW2ER,Unknown,"เขตสายไหม,ฝ่ายโยธา เขตสายไหม",พื้นชำรุดครับ,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.62674,13.92760",89 ซอย เขื่อนขันธ์ 2 แขวง สายไหม เขตสายไหม กรุ...,สายไหม,สายไหม,กรุงเทพมหานคร,2022-02-01 11:02:29.400946+00:00,เสร็จสิ้น,-1,0,2023-07-12 03:09:21.489869+00:00,13.92760,100.62674,1,1
34,2022-62HXGH,{ถนน},"เขตสาทร,สำนักการจราจรและขนส่ง กรุงเทพมหานคร (ส...",เรื่องทางม้าลายหายไป บริเวณสี่แยกถนนจันทร์-เซน...,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.52680,13.70629",1878 ซอย จันทน์ 18/8 แขวง ทุ่งวัดดอน เขต สาทร ...,ทุ่งวัดดอน,สาทร,กรุงเทพมหานคร,2022-02-01 18:11:20.963592+00:00,เสร็จสิ้น,1,0,2023-02-10 09:48:30.498845+00:00,13.70629,100.52680,1,1
35,2022-CGYXCQ,Unknown,"กรมป้องกันและบรรเทาสาธารณภัย,ศูนย์อำนวยการบรรเ...",สีเส้นไม่ชัดเจน #ทางม้าลาย,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.54218,13.75541",90/5 ถนนราชปรารภ แขวง ถนนพญาไท เขตราชเทวี กรุง...,ถนนพญาไท,ราชเทวี,กรุงเทพมหานคร,2022-02-03 09:25:56.799171+00:00,เสร็จสิ้น,-1,0,2024-03-05 11:50:46.435851+00:00,13.75541,100.54218,1,1
36,2022-7UDVXF,Unknown,"กรมป้องกันและบรรเทาสาธารณภัย,ศูนย์อำนวยการบรรเ...",สีเส้นไม่ชัดเจน #ทางม้าลาย,https://storage.googleapis.com/traffy_public_b...,https://storage.googleapis.com/traffy_public_b...,"100.51875,13.71870",เลขที่ 160 ถ. สาทรเหนือ แขวง สีลม เขตบางรัก กร...,สีลม,บางรัก,กรุงเทพมหานคร,2022-02-04 04:26:51.203566+00:00,เสร็จสิ้น,-1,0,2024-03-05 11:50:59.575234+00:00,13.71870,100.51875,1,1
37,2022-C9AX76,{แสงสว่าง},"กรมป้องกันและบรรเทาสาธารณภัย,ศูนย์อำนวยการบรรเ...",ไม่มีไฟส่องสว่าง #ทางม้าลาย,https://storage.googleapis.com/traffy_public_b...,NaN,"100.50906,13.77239",12/1 ถนน อู่ทองนอก แขวง ดุสิต เขตดุสิต กรุงเทพ...,ดุสิต,ดุสิต,กรุงเทพมหานคร,2022-02-04 04:57:37.136868+00:00,เสร็จสิ้น,-1,0,2024-03-05 11:51:11.518940+00:00,13.77239,100.50906,1,0
38,2022-Q2Z98G,Unknown,"กรมป้องกันและบรรเทาสาธารณภัย,ศูนย์อำนวยการบรรเ...",ไม่มีไฟสัญญาณ #ทางม้าลาย,https://storage.googleapis.com/traffy_public_b...,NaN,"100.52558,13.72543",แยกเดโช 703 ถนน สีลม แขวง สีลม เขตบางรัก กรุงเ...,สี่พระยา,บางรัก,กรุงเทพมหานคร,2022-02-04 04:59:07.057648+00:00,เสร็จสิ้น,5,0,2024-03-05 11:51:23.438590+00:00,13.72543,100.52558,1,0
39,2022-DY7YCJ,Unknown,"กรมป้องกันและบรรเทาสาธารณภัย,ศูนย์อำนวยการบรรเ...",สีเส้นไม่ชัดเจน #ทางม้าลาย,https://storage.googleapis.com/traffy_public_b...,NaN,"100.54114,13.79787",101/74 กำแพงเพชร 1 แขวง จตุจักร เขตจตุจักร กรุ...,จตุจักร,จตุจักร,กรุงเทพมหานคร,2022-02-04 05:35:55.239586+00:00,เสร็จสิ้น,5,0,2024-05-15 09:04:12.523726+00:00,13.79787,100.54114,1,0

## Save Cleaned Data

In [8]:
output_path = '../data_clean/bangkok_traffy_clean.csv'
import os
os.makedirs('../data_clean', exist_ok=True)
df.to_csv(output_path, index=False)
output_path

'../data_clean/bangkok_traffy_clean.csv'